services:
  



services:

  wpp:
    image: devlikeapro/waha:latest
    container_name: wpp
    restart: always

    ports:
      - '3000:3000'

  api:
    build:
      context: .
      dockerfile: dockerfile.api_chat
    container_name: api
    ports:
      - '5000:5000'
  volumes:
      - .:/app
      - ./chroma_data:/app/chroma_data
